# NFL Match Data - 2020 Season Analysis

In [20]:
import pandas as pd

In [21]:
df = pd.read_csv("Data/processed_game_history.csv")
df = df.drop(["Unnamed: 0", "AtHome"], axis=1)

In [22]:
df_2020 = df[df["Season"] == 2020]
print(f"Number of games played: {len(df_2020)}")

Number of games played: 269

In [23]:
df_2020.head()

,Rk,Week,Day,Date,Winner/tie,Loser/tie,PtsW,PtsL,YdsW,TOW,YdsL,TOL,HomeTeam,Season,PtsMargin,TieGame,ModifiedWeek
266,267,1,Sun,2020-09-13,Los Angeles Rams,Dallas Cowboys,20,17,422.0,1.0,380.0,0.0,Los Angeles Rams,2020,3,0,1
267,268,12,Sun,2020-11-29,New England Patriots,Arizona Cardinals,20,17,179.0,2.0,298.0,1.0,New England Patriots,2020,3,0,12
268,269,14,Sun,2020-12-13,Los Angeles Chargers,Atlanta Falcons,20,17,345.0,1.0,319.0,3.0,Los Angeles Chargers,2020,3,0,14
483,212,7,Sun,2020-10-25,New Orleans Saints,Carolina Panthers,27,24,415.0,1.0,283.0,0.0,New Orleans Saints,2020,3,0,7
484,213,7,Sun,2020-10-25,Pittsburgh Steelers,Tennessee Titans,27,24,362.0,3.0,292.0,0.0,Tennessee Titans,2020,3,0,7

In [24]:
wk_occurence_2020 = df_2020.groupby(["Week"]).size().reset_index().rename(columns={0:"count"}).sort_values(by="count", ascending=False)
wk_occurence_2020

                 Week  count
0                   1     16
6                  15     16
9                   2     16
8                  17     16
7                  16     16
10                  3     16
5                  14     16
3                  12     16
4                  13     15
11                  4     15
2                  11     14
1                  10     14
12                  5     14
13                  6     14
14                  7     14
15                  8     14
16                  9     14
20          Wild Card      6
18           Division      4
17  Championship Game      2
19         Super Bowl      1